// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _ProyectoFinal.Data;

namespace ProyectoFinal.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    [Migration("20201101175017_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("_ProyectoFinal.Data.Detalle", b =>
                {
                    b.Property<int>("Id_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecursoId_Recurso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TareaId_Tarea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Detalle");

                    b.HasIndex("RecursoId_Recurso");

                    b.HasIndex("TareaId_Tarea");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("_ProyectoFinal.Data.Recurso", b =>
                {
                    b.Property<int>("Id_Recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId_User")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Recurso");

                    b.HasIndex("UsuarioId_User");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("_ProyectoFinal.Data.Tarea", b =>
                {
                    b.Property<int>("Id_Tarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Tarea");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("_ProyectoFinal.Data.Usuario", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(20);

                    b.HasKey("Id_User");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("_ProyectoFinal.Data.Detalle", b =>
                {
                    b.HasOne("_ProyectoFinal.Data.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId_Recurso");

                    b.HasOne("_ProyectoFinal.Data.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId_Tarea");
                });

            modelBuilder.Entity("_ProyectoFinal.Data.Recurso", b =>
                {
                    b.HasOne("_ProyectoFinal.Data.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId_User");
                });
#pragma warning restore 612, 618
        }
    }
}
