// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParcialEssesIgnacio;

namespace ParcialEssesIgnacio.Migrations
{
    [DbContext(typeof(TareaDbContext))]
    [Migration("20201010222624_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("ParcialEssesIgnacio.Detalle", b =>
                {
                    b.Property<int>("Id_Detalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RecursoId_Recurso")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TareaId_Tarea")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Detalle");

                    b.HasIndex("RecursoId_Recurso");

                    b.HasIndex("TareaId_Tarea");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("ParcialEssesIgnacio.Recurso", b =>
                {
                    b.Property<int>("Id_Recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId_User")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Recurso");

                    b.HasIndex("UsuarioId_User");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("ParcialEssesIgnacio.Tarea", b =>
                {
                    b.Property<int>("Id_Tarea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estimacion")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponsableId_Recurso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Tarea");

                    b.HasIndex("ResponsableId_Recurso");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("ParcialEssesIgnacio.Usuario", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clave")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_User");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ParcialEssesIgnacio.Detalle", b =>
                {
                    b.HasOne("ParcialEssesIgnacio.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId_Recurso");

                    b.HasOne("ParcialEssesIgnacio.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId_Tarea");
                });

            modelBuilder.Entity("ParcialEssesIgnacio.Recurso", b =>
                {
                    b.HasOne("ParcialEssesIgnacio.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId_User");
                });

            modelBuilder.Entity("ParcialEssesIgnacio.Tarea", b =>
                {
                    b.HasOne("ParcialEssesIgnacio.Recurso", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId_Recurso");
                });
#pragma warning restore 612, 618
        }
    }
}
