// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20201006;

namespace _20201006.Migrations
{
    [DbContext(typeof(TareasDbContext))]
    [Migration("20201007010616_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("_20201006.Usuario", b =>
                {
                    b.Property<int>("Codigo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clave")
                        .HasColumnName("Password")
                        .HasColumnType("char(20)");

                    b.Property<int>("Nombre")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(50);

                    b.HasKey("Codigo");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
